name: Update FPL Data

on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours (UTC)
  workflow_dispatch:

concurrency:
  group: fpl-data
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Node 20 includes fetch() natively; we don't need npm install
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build data.json
        run: node scripts/build.mjs

      - name: Commit & push (rebase-safe)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Update data.json"
            # rebase onto latest main to avoid non-fast-forward errors
            git fetch origin main
            git pull --rebase origin main
            git push origin HEAD:main
          else
            echo "No changes."
          fi