name: Update FPL Data

on:
  schedule:
    - cron: "0 */3 * * *"   # every 3 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: fpl-build
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0            # allow rebase

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps (if any)
        run: |
          if [ -f package-lock.json ] || [ -f pnpm-lock.yaml ] || [ -f yarn.lock ]; then
            npm ci || npm install
          else
            echo "No lockfile; skipping install"
          fi

      - name: Build data.json
        run: node scripts/build.mjs

      - name: Commit & push (rebase-safe)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data.json
            git commit -m "Update data.json"
            git fetch origin main
            git pull --rebase origin main
            git push origin HEAD:main
          else
            echo "No changes."
          fi